[tool.coverage.run]
command_line = "-m pytest"
source = ["sewer"]
omit = [
    "*test*",
    "*__init__.py"
]
data_file = "tests/coverage"

[tool.coverage.report]
fail_under = 85
show_missing = true
omit = [
    "*__main__.py",
    "*acme.py",
    "*cli.py"
]

[tool.coverage.html]
directory = "tests/data/htmlcov"

[tool.pytest.ini_options]
console_output_style = "classic"
addopts = "--color=no"

[tool.black]
line-length = 100
target-version = [
    "py39"
]
